#! /bin/bash 

# 配置ftp 
FTP_SERVER=112.74.72.68 
USER="ios" 
PASSWORD="xID9gdYH" 
# FTP_PATH="/wwwroot/www_hey900_com/site/ios/iostest" 
# LOCAL_PATH="/Users/winter/Desktop/demo/QRCode/ipa_build" 

if [ $# -lt 1 ];then
	echo "Error! Should enter the FTP_PATH."
	exit 2
fi

LOCAL_PATH=$1
FTP_PATH=$2
echo $LOCAL_PATH
echo $FTP_PATH

if [[ ! -d $LOCAL_PATH ]]; then
	echo "$LOCAL_PATH This path doesn't exit."
	exit 2
fi

# 本地文件目录存在 执行ftp 命令
ftp -n -i <<!
	open $FTP_SERVER
	user $USER $PASSWORD
	passive
	bin
	cd $FTP_PATH
	lcd $LOCAL_PATH
	mput *
	ls
	close
	bye
	!